// Crumbs.hyd menu data — extracted from brand cards
window.CRUMBS_DATA = {
  brand: {
    name: "Crumbs.hyd",
    handle: "@crumbs.hyd",
    tagline: "small ways of being loved",
    location: "Mehdipatnam, Hyderabad",
    rating: 4.9,
    reviews: 312,
  },
  categories: [
    { id: "cookies",  label: "Cookies" },
    { id: "premium",  label: "Premium boxes" },
    { id: "brownies", label: "Brownies & brookies" },
    { id: "tubs",     label: "Cake-tubs" },
    { id: "pistachio",label: "Pistachio cakes" },
  ],
  items: [
    // ---- COOKIES (single) ----
    { id: "cc-classic", cat: "cookies", name: "Choco-chunk cookie",
      blurb: "the one that started fights between siblings. soft middle, melty pools.",
      more: "made with two kinds of chocolate — chunks that stay melty even after a day, folded into a soft, slightly under-baked middle. the cookie that converted half our followers.",
      variants: [{ label: "classic", price: 125 }],
      tag: "bestseller", images: [] },
    { id: "cnc", cat: "cookies", name: "Cookies & Cream choco-chunk",
      blurb: "oreo bits folded in. like the cookie aisle had a baby.",
      more: "real oreo crumbles + white chocolate chunks in our signature dough. the one for people who can't pick a side.",
      variants: [{ label: "classic", price: 130 }], images: [] },
    { id: "pb-caramel", cat: "cookies", name: "PB & caramel choco-chunk",
      blurb: "salty peanut butter, gooey caramel. dangerous on a tuesday.",
      more: "smooth peanut butter swirls, salted caramel pockets, dark chocolate chunks. genuinely a 3pm event.",
      variants: [{ label: "classic", price: 135 }],
      tag: "spicy fav", images: [] },
    { id: "pista-white", cat: "cookies", name: "Pistachio white choco-chunk",
      blurb: "real pistachios, white chocolate. the one you save for yourself.",
      more: "roasted pistachios, real ones, with creamy white chocolate. soft middle, slight crunch on the edges.",
      variants: [{ label: "classic", price: 155 }], images: [] },

    // ---- PREMIUM BOXES ----
    { id: "duel", cat: "premium", name: "Milk & Dark choco-chunk duel",
      blurb: "two chocolates, no notes.",
      more: "milk and dark chocolate, both chunked, layered into the same dough. for the people who can never just pick one.",
      variants: [{ label: "box of 6", price: 995 }, { label: "box of 12", price: 1985 }], images: [] },
    { id: "hazelnut", cat: "premium", name: "Hazelnut center-filled craze",
      blurb: "molten hazelnut middle. yes, like that one spread.",
      more: "soft choco-chunk shell with a slow-pour hazelnut center. warm one for 8 seconds and thank us later.",
      variants: [{ label: "box of 6", price: 1170 }, { label: "box of 12", price: 2335 }],
      tag: "everyone's into this", images: [] },
    { id: "biscoff", cat: "premium", name: "Biscoff & white choco overload",
      blurb: "biscoff chunks, white choc puddles. unserious in the best way.",
      more: "lotus biscoff broken right into the dough + white chocolate puddles. caramelly, creamy, a full vibe.",
      variants: [{ label: "box of 6", price: 1530 }, { label: "box of 12", price: 3060 }], images: [] },
    { id: "assorted-prem", cat: "premium", name: "Assorted (classic + hazelnut + biscoff)",
      blurb: "one of each, for the indecisive. or generous.",
      more: "a curated mix: signature choco-chunk, hazelnut center-filled, biscoff overload — in equal parts. great gift box.",
      variants: [{ label: "box of 6", price: 1210 }, { label: "box of 12", price: 2420 }], images: [] },

    // ---- BROWNIES ----
    { id: "br-classic", cat: "brownies", name: "Choco-chunk brownies",
      blurb: "fudgy, crackly top, slightly underbaked centre. on purpose.",
      more: "rich chocolate brownie with chunks throughout. shiny crackly top, soft fudgy middle. choose your toppings on add.",
      variants: [{ label: "6 pieces", price: 375 }, { label: "9 pieces", price: 540 }],
      toppings: [
        { id: "chocospread", label: "chocolate spread", price: 30 },
        { id: "sprinkles", label: "sprinkles", price: 20 },
        { id: "white-choc", label: "white choc drizzle", price: 30 },
        { id: "caramel", label: "salted caramel", price: 40 },
        { id: "biscoff", label: "biscoff crumble", price: 40 },
        { id: "nuts", label: "toasted nuts", price: 35 },
      ],
      images: [],
    },
    { id: "brookie", cat: "brownies", name: "Choco-chunk brookies",
      blurb: "cookie + brownie. couldn't pick, didn't have to.",
      more: "half cookie, half brownie, layered. crispy top from the cookie side, gooey middle from the brownie side.",
      variants: [{ label: "6 pieces", price: 375 }, { label: "9 pieces", price: 540 }],
      toppings: [
        { id: "chocospread", label: "chocolate spread", price: 30 },
        { id: "sprinkles", label: "sprinkles", price: 20 },
        { id: "white-choc", label: "white choc drizzle", price: 30 },
        { id: "caramel", label: "salted caramel", price: 40 },
        { id: "biscoff", label: "biscoff crumble", price: 40 },
      ],
      images: [],
    },

    // ---- CAKE TUBS ----
    { id: "tub-bliss", cat: "tubs", name: "Chocolate bliss tub",
      blurb: "chocolate cake + chocolate filling. a whole love letter.",
      more: "soft chocolate cake layered with silky chocolate filling, in a spoonable tub. perfect-portion sized.",
      variants: [{ label: "tub", price: 425 }], images: [] },
    { id: "tub-cnc", cat: "tubs", name: "Cookies & cream tub",
      blurb: "cookies-and-cream cake + white chocolate filling.",
      more: "oreo-laced cake with a smooth white chocolate filling. layered, scoopable, dangerous.",
      variants: [{ label: "tub", price: 425 }], images: [] },
    { id: "tub-half", cat: "tubs", name: "Half vanilla tub",
      blurb: "choco-chunk vanilla cake + choco-vanilla filling.",
      more: "vanilla cake with chocolate chunks, layered with a chocolate-vanilla cream. for the can't-decide people.",
      variants: [{ label: "tub", price: 425 }], images: [] },
    { id: "tub-pb", cat: "tubs", name: "PB & caramel tub",
      blurb: "chocolate cake + peanut butter & caramel filling.",
      more: "chocolate cake layered with peanut butter cream and pockets of salted caramel. salty-sweet, loud.",
      variants: [{ label: "tub", price: 450 }], images: [] },

    // ---- PISTACHIO CAKES ----
    { id: "tres-leches", cat: "pistachio", name: "Pistachio tres leches",
      blurb: "soaked-milk cake. real pistachios. 550–600g.",
      more: "three-milk soaked sponge with real roasted pistachios folded in. light, soft, melts on the tongue. serves 4–6.",
      variants: [{ label: "whole cake", price: 895 }], images: [] },
    { id: "tres-kunafa", cat: "pistachio", name: "Tres leches + kunafa layered",
      blurb: "crunchy kunafa, soft milky cake, pistachio everywhere. 600–700g.",
      more: "tres leches base layered with crispy kunafa threads, pistachio cream and rose petals on top. crunchy then soft. 600–700g, serves 4–6.",
      variants: [{ label: "whole cake", price: 1295 }],
      tag: "the showstopper", images: [] },
  ],
};
