-- Seed data for Crumbs.hyd. Run after schema.sql.

insert into crumbs_hyd_categories(id,label,sort_order) values('cookies','Cookies',1) on conflict (id) do update set label=excluded.label, sort_order=excluded.sort_order;
insert into crumbs_hyd_categories(id,label,sort_order) values('premium','Premium boxes',2) on conflict (id) do update set label=excluded.label, sort_order=excluded.sort_order;
insert into crumbs_hyd_categories(id,label,sort_order) values('brownies','Brownies & brookies',3) on conflict (id) do update set label=excluded.label, sort_order=excluded.sort_order;
insert into crumbs_hyd_categories(id,label,sort_order) values('tubs','Cake-tubs',4) on conflict (id) do update set label=excluded.label, sort_order=excluded.sort_order;
insert into crumbs_hyd_categories(id,label,sort_order) values('pistachio','Pistachio cakes',5) on conflict (id) do update set label=excluded.label, sort_order=excluded.sort_order;

insert into crumbs_hyd_items(id,cat,name,blurb,more,tag,variants,toppings,sort_order) values('cc-classic','cookies','Choco-chunk cookie','the one that started fights between siblings. soft middle, melty pools.','made with two kinds of chocolate — chunks that stay melty even after a day, folded into a soft, slightly under-baked middle. the cookie that converted half our followers.','bestseller','[{"label":"classic","price":125}]'::jsonb,'[]'::jsonb,1) on conflict (id) do update set cat=excluded.cat,name=excluded.name,blurb=excluded.blurb,more=excluded.more,tag=excluded.tag,variants=excluded.variants,toppings=excluded.toppings,sort_order=excluded.sort_order;
insert into crumbs_hyd_items(id,cat,name,blurb,more,tag,variants,toppings,sort_order) values('cnc','cookies','Cookies & Cream choco-chunk','oreo bits folded in. like the cookie aisle had a baby.','real oreo crumbles + white chocolate chunks in our signature dough. the one for people who can''t pick a side.',null,'[{"label":"classic","price":130}]'::jsonb,'[]'::jsonb,2) on conflict (id) do update set cat=excluded.cat,name=excluded.name,blurb=excluded.blurb,more=excluded.more,tag=excluded.tag,variants=excluded.variants,toppings=excluded.toppings,sort_order=excluded.sort_order;
insert into crumbs_hyd_items(id,cat,name,blurb,more,tag,variants,toppings,sort_order) values('pb-caramel','cookies','PB & caramel choco-chunk','salty peanut butter, gooey caramel. dangerous on a tuesday.','smooth peanut butter swirls, salted caramel pockets, dark chocolate chunks. genuinely a 3pm event.','spicy fav','[{"label":"classic","price":135}]'::jsonb,'[]'::jsonb,3) on conflict (id) do update set cat=excluded.cat,name=excluded.name,blurb=excluded.blurb,more=excluded.more,tag=excluded.tag,variants=excluded.variants,toppings=excluded.toppings,sort_order=excluded.sort_order;
insert into crumbs_hyd_items(id,cat,name,blurb,more,tag,variants,toppings,sort_order) values('pista-white','cookies','Pistachio white choco-chunk','real pistachios, white chocolate. the one you save for yourself.','roasted pistachios, real ones, with creamy white chocolate. soft middle, slight crunch on the edges.',null,'[{"label":"classic","price":155}]'::jsonb,'[]'::jsonb,4) on conflict (id) do update set cat=excluded.cat,name=excluded.name,blurb=excluded.blurb,more=excluded.more,tag=excluded.tag,variants=excluded.variants,toppings=excluded.toppings,sort_order=excluded.sort_order;
insert into crumbs_hyd_items(id,cat,name,blurb,more,tag,variants,toppings,sort_order) values('duel','premium','Milk & Dark choco-chunk duel','two chocolates, no notes.','milk and dark chocolate, both chunked, layered into the same dough. for the people who can never just pick one.',null,'[{"label":"box of 6","price":995},{"label":"box of 12","price":1985}]'::jsonb,'[]'::jsonb,5) on conflict (id) do update set cat=excluded.cat,name=excluded.name,blurb=excluded.blurb,more=excluded.more,tag=excluded.tag,variants=excluded.variants,toppings=excluded.toppings,sort_order=excluded.sort_order;
insert into crumbs_hyd_items(id,cat,name,blurb,more,tag,variants,toppings,sort_order) values('hazelnut','premium','Hazelnut center-filled craze','molten hazelnut middle. yes, like that one spread.','soft choco-chunk shell with a slow-pour hazelnut center. warm one for 8 seconds and thank us later.','everyone''s into this','[{"label":"box of 6","price":1170},{"label":"box of 12","price":2335}]'::jsonb,'[]'::jsonb,6) on conflict (id) do update set cat=excluded.cat,name=excluded.name,blurb=excluded.blurb,more=excluded.more,tag=excluded.tag,variants=excluded.variants,toppings=excluded.toppings,sort_order=excluded.sort_order;
insert into crumbs_hyd_items(id,cat,name,blurb,more,tag,variants,toppings,sort_order) values('biscoff','premium','Biscoff & white choco overload','biscoff chunks, white choc puddles. unserious in the best way.','lotus biscoff broken right into the dough + white chocolate puddles. caramelly, creamy, a full vibe.',null,'[{"label":"box of 6","price":1530},{"label":"box of 12","price":3060}]'::jsonb,'[]'::jsonb,7) on conflict (id) do update set cat=excluded.cat,name=excluded.name,blurb=excluded.blurb,more=excluded.more,tag=excluded.tag,variants=excluded.variants,toppings=excluded.toppings,sort_order=excluded.sort_order;
insert into crumbs_hyd_items(id,cat,name,blurb,more,tag,variants,toppings,sort_order) values('assorted-prem','premium','Assorted (classic + hazelnut + biscoff)','one of each, for the indecisive. or generous.','a curated mix: signature choco-chunk, hazelnut center-filled, biscoff overload — in equal parts. great gift box.',null,'[{"label":"box of 6","price":1210},{"label":"box of 12","price":2420}]'::jsonb,'[]'::jsonb,8) on conflict (id) do update set cat=excluded.cat,name=excluded.name,blurb=excluded.blurb,more=excluded.more,tag=excluded.tag,variants=excluded.variants,toppings=excluded.toppings,sort_order=excluded.sort_order;
insert into crumbs_hyd_items(id,cat,name,blurb,more,tag,variants,toppings,sort_order) values('br-classic','brownies','Choco-chunk brownies','fudgy, crackly top, slightly underbaked centre. on purpose.','rich chocolate brownie with chunks throughout. shiny crackly top, soft fudgy middle. choose your toppings on add.',null,'[{"label":"6 pieces","price":375},{"label":"9 pieces","price":540}]'::jsonb,'[{"id":"chocospread","label":"chocolate spread","price":30},{"id":"sprinkles","label":"sprinkles","price":20},{"id":"white-choc","label":"white choc drizzle","price":30},{"id":"caramel","label":"salted caramel","price":40},{"id":"biscoff","label":"biscoff crumble","price":40},{"id":"nuts","label":"toasted nuts","price":35}]'::jsonb,9) on conflict (id) do update set cat=excluded.cat,name=excluded.name,blurb=excluded.blurb,more=excluded.more,tag=excluded.tag,variants=excluded.variants,toppings=excluded.toppings,sort_order=excluded.sort_order;
insert into crumbs_hyd_items(id,cat,name,blurb,more,tag,variants,toppings,sort_order) values('brookie','brownies','Choco-chunk brookies','cookie + brownie. couldn''t pick, didn''t have to.','half cookie, half brownie, layered. crispy top from the cookie side, gooey middle from the brownie side.',null,'[{"label":"6 pieces","price":375},{"label":"9 pieces","price":540}]'::jsonb,'[{"id":"chocospread","label":"chocolate spread","price":30},{"id":"sprinkles","label":"sprinkles","price":20},{"id":"white-choc","label":"white choc drizzle","price":30},{"id":"caramel","label":"salted caramel","price":40},{"id":"biscoff","label":"biscoff crumble","price":40}]'::jsonb,10) on conflict (id) do update set cat=excluded.cat,name=excluded.name,blurb=excluded.blurb,more=excluded.more,tag=excluded.tag,variants=excluded.variants,toppings=excluded.toppings,sort_order=excluded.sort_order;
insert into crumbs_hyd_items(id,cat,name,blurb,more,tag,variants,toppings,sort_order) values('tub-bliss','tubs','Chocolate bliss tub','chocolate cake + chocolate filling. a whole love letter.','soft chocolate cake layered with silky chocolate filling, in a spoonable tub. perfect-portion sized.',null,'[{"label":"tub","price":425}]'::jsonb,'[]'::jsonb,11) on conflict (id) do update set cat=excluded.cat,name=excluded.name,blurb=excluded.blurb,more=excluded.more,tag=excluded.tag,variants=excluded.variants,toppings=excluded.toppings,sort_order=excluded.sort_order;
insert into crumbs_hyd_items(id,cat,name,blurb,more,tag,variants,toppings,sort_order) values('tub-cnc','tubs','Cookies & cream tub','cookies-and-cream cake + white chocolate filling.','oreo-laced cake with a smooth white chocolate filling. layered, scoopable, dangerous.',null,'[{"label":"tub","price":425}]'::jsonb,'[]'::jsonb,12) on conflict (id) do update set cat=excluded.cat,name=excluded.name,blurb=excluded.blurb,more=excluded.more,tag=excluded.tag,variants=excluded.variants,toppings=excluded.toppings,sort_order=excluded.sort_order;
insert into crumbs_hyd_items(id,cat,name,blurb,more,tag,variants,toppings,sort_order) values('tub-half','tubs','Half vanilla tub','choco-chunk vanilla cake + choco-vanilla filling.','vanilla cake with chocolate chunks, layered with a chocolate-vanilla cream. for the can''t-decide people.',null,'[{"label":"tub","price":425}]'::jsonb,'[]'::jsonb,13) on conflict (id) do update set cat=excluded.cat,name=excluded.name,blurb=excluded.blurb,more=excluded.more,tag=excluded.tag,variants=excluded.variants,toppings=excluded.toppings,sort_order=excluded.sort_order;
insert into crumbs_hyd_items(id,cat,name,blurb,more,tag,variants,toppings,sort_order) values('tub-pb','tubs','PB & caramel tub','chocolate cake + peanut butter & caramel filling.','chocolate cake layered with peanut butter cream and pockets of salted caramel. salty-sweet, loud.',null,'[{"label":"tub","price":450}]'::jsonb,'[]'::jsonb,14) on conflict (id) do update set cat=excluded.cat,name=excluded.name,blurb=excluded.blurb,more=excluded.more,tag=excluded.tag,variants=excluded.variants,toppings=excluded.toppings,sort_order=excluded.sort_order;
insert into crumbs_hyd_items(id,cat,name,blurb,more,tag,variants,toppings,sort_order) values('tres-leches','pistachio','Pistachio tres leches','soaked-milk cake. real pistachios. 550–600g.','three-milk soaked sponge with real roasted pistachios folded in. light, soft, melts on the tongue. serves 4–6.',null,'[{"label":"whole cake","price":895}]'::jsonb,'[]'::jsonb,15) on conflict (id) do update set cat=excluded.cat,name=excluded.name,blurb=excluded.blurb,more=excluded.more,tag=excluded.tag,variants=excluded.variants,toppings=excluded.toppings,sort_order=excluded.sort_order;
insert into crumbs_hyd_items(id,cat,name,blurb,more,tag,variants,toppings,sort_order) values('tres-kunafa','pistachio','Tres leches + kunafa layered','crunchy kunafa, soft milky cake, pistachio everywhere. 600–700g.','tres leches base layered with crispy kunafa threads, pistachio cream and rose petals on top. crunchy then soft. 600–700g, serves 4–6.','the showstopper','[{"label":"whole cake","price":1295}]'::jsonb,'[]'::jsonb,16) on conflict (id) do update set cat=excluded.cat,name=excluded.name,blurb=excluded.blurb,more=excluded.more,tag=excluded.tag,variants=excluded.variants,toppings=excluded.toppings,sort_order=excluded.sort_order;
